# Site
name: 'jefdewitt.com'
description: 'jefdewitt.com is my personal window to the Internets.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicons/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'f/xzbyqlnz' # obtained from FormSpree

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    jef:
      name:          Jef DeWitt
      site:          https://www.jefdewitt.com
      avatar:        assets/images/jef-avatar.jpg
      image:         assets/images/jef-stuntin-min.jpg
      bio1:          By my mid-thirties I was living in active addiction, divorced, and unemployed. I was a mess. And it was a profound wake up call.
      bio2:          I began rebuilding my life after a simple realization; that living in addiction is incredibly hard work. I found hope in that. Because I recognized that if I applied that same ethic to educating and improving myself, it gave me a chance. 
      bio3:          Through my recovery and years in therapy, I got a humbling education in self-discipline, emotional intelligence, and practical lessons in healthy relationships. I humbly share the amalgamation of all my research and experimentation in an honest effort to help heal; myself and others.
      bio4:          Views expressed on this site are solely my own and do not reflect the opinions or positions of any organizations I currently am or have previously been affiliated with. 
      email:         jefdewitt@gmail.com
      linkedin:      https://www.linkedin.com/in/jefdewitt/
      instagram:     https://www.instagram.com/jefdewitt
      medium:        https://www.medium.com/@jefdewitt
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: jef
      avatar: assets/images/jef-avatar.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

  # all painting images
  - scope:
      path: "assets/images/paintings"
    values:
      image: true
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]