# Site
name: 'jefdewitt.com'
description: 'jefdewitt.com is my personal window to the Internets.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'f/xzbyqlnz' # obtained from FormSpree
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    jef:
      name:          Jef
      site:          https://www.jefdewitt.com
      avatar:        assets/images/jef-stuntin-min.JPG
      bio1:          Hey, I'm Jef, owner of the site. I'm a software engineer. I'm an enthusiastic teacher and lifelong leaner. I'm a volunteer mentor for aspiring tech students in web technologies. I earned my BS in Computer Science from Southern New Hampshire Univeristy in 2021.
      bio2:          Here's a little extra on me. I began my career in tech at 35, earning entry into a field where I was already older than a lot of senior devs. It's been quite a journey, full of challenges as well as chances to develop skills that translate across many fields. 
      bio3:          I'm also a passionate mental health advocate. I hope to encourage others as I share experiences from my own struggles with substance abuse in an honest effort to help heal all that goes along with the psychology of battling addiction.
      email:         jefdewitt@gmail.com
      linkedin:      https://www.linkedin.com/in/jefdewitt/
      instagram:     https://www.instagram.com/jefdewitt
      medium:        https://www.medium.com/@jefdewitt
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

  # all painting images
  - scope:
      path: "assets/images/paintings"
    values:
      image: true
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]