# Site
name: 'jefdewitt.com'
description: 'jefdewitt.com is my personal window to the Internets.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicons/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'f/xzbyqlnz' # obtained from FormSpree

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    jef:
      name:          Jef DeWitt
      site:          https://www.jefdewitt.com
      avatar:        assets/images/jef-avatar.jpg
      image:         assets/images/jef-stuntin-min.jpg
      bio1:          I'm a software engineer, I'm an enthusiastic teacher, and lifelong leaner. I'm a volunteer mentor for aspiring tech students in web technologies. I earned my BS in Computer Science from Southern New Hampshire University in 2021.
      bio2:          Here's a little extra on me. I began my career in tech at 35, earning entry into a field where I was already older than a lot of senior devs. It's been a journey full of challenges. One that developed skills that translate across many fields. 
      bio3:          I'm also a passionate mental health advocate. I aim to encourage others as I share experiences from my own struggles with substance abuse. It's an honest effort to help heal all that goes along with the psychology of battling addiction.
      bio4:          Views expressed on this site are solely my own and do not reflect the opinions or positions of any organizations I currently am or have previously been affiliated with. 
      email:         jefdewitt@gmail.com
      linkedin:      https://www.linkedin.com/in/jefdewitt/
      instagram:     https://www.instagram.com/jefdewitt
      medium:        https://www.medium.com/@jefdewitt
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: jef
      avatar: assets/images/jef-avatar.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

  # all painting images
  - scope:
      path: "assets/images/paintings"
    values:
      image: true
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10
paginate_path: "/blog/page:num/"

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]